ai_ipass:
  host: 0.0.0.0
  port: 8080

vector_store:
  type: pinecone
  api_key: YOUR_API_KEY
  environment: production

ai_model:
  type: openai
  api_key: YOUR_API_KEY
  model: gpt-4

systems:
  - name: System A
    url: https://systema.example.com
    auth:
      type: oauth2
      client_id: CLIENT_ID
      client_secret: CLIENT_SECRET
  - name: System B
    url: https://systemb.example.com
    auth:
      type: api_key
      key: API_KEY